/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/result/SussessResult copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorPage: typeof import('./src/components/error/ErrorPage.vue')['default']
    FailResult: typeof import('./src/components/result/FailResult.vue')['default']
    InfoResult: typeof import('./src/components/result/InfoResult.vue')['default']
    MessageApi: typeof import('./src/components/MessageApi.vue')['default']
    NoPermissionPage: typeof import('./src/components/error/NoPermissionPage.vue')['default']
    NotFoundPage: typeof import('./src/components/error/NotFoundPage.vue')['default']
    Redirect: typeof import('./src/components/Redirect.vue')['default']
    RedirectPage: typeof import('./src/components/RedirectPage.vue')['default']
    ReloadPage: typeof import('./src/components/ReloadPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessResult: typeof import('./src/components/result/SuccessResult.vue')['default']
    SussessResult: typeof import('./src/components/result/SussessResult.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TabPage: typeof import('./src/components/TabPage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
